version: '3'

services:


    gotest-1: 
        container_name: arbi
        environment:
            VAR: value
        build: . 
        volumes: 
        - ./logs:/app/logs #for logs
        restart: always
